### ISSUE TITLE
The sample json data file in day 40-42 is not in json format

### ISSUE THREAD

**Issue by vipinreyaroth** [talkpython/100daysofcode-with-python-course#15]
Hi Guys
I was trying to load the 100daysofcode-with-python-course/days/40-42-json-data/code/mount-data.txt using json.load() module and I'm getting the error 'json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes:'.
As per stackoverflow article https://stackoverflow.com/questions/39491420/python-jsonexpecting-property-name-enclosed-in-double-quotes, the format is not correct. Can you confirm pls?

- Vipin

**Comment by hobojoe1848** [comment]
Hi Vipin!

Let me take a look mate. Will get back to you shortly.

Cheers
Julian

**Comment by hobojoe1848** [comment]
Hi Vipin,

You're correct! JSON requires double quotes and the output I have in the .txt file is from the formatted json output in my Python script. Even so, given it's just a plain text file, there are a few things that are preventing it from being read in as JSON.

I need to look into how to get a native JSON file created for this. Might see if I can pull straight from the Blizzard API and dump straight into a JSON file.

**Comment by mikeckennedy** [comment]
Hi guys. The contents of `mount.txt` are actually Python not JSON. I loaded that and converted it to JSON here:

https://github.com/talkpython/100daysofcode-with-python-course/blob/master/days/40-42-json-data/code/mount-data.json

See https://github.com/talkpython/100daysofcode-with-python-course/commit/a991f6e4338054a14b1dc8db27b4217f7e326609
