### ISSUE TITLE
Itertools traffic light task

### ISSUE THREAD

**Issue by ignazwrangel** [talkpython/100daysofcode-with-python-course#18]
Hi, I think there's some missing info in the itertools unit readme. It says to try to complete the task before watching the video, but the only description of the task in the readme is "create a script that simulates traffic lights" - it's not obvious what it is.

**Comment by mikeckennedy** [comment]
Hi @bbelderbos  @hobojoe1848 not sure which of you wrote that chapter. Could you have a look?

Thanks for the heads up @ignazwrangel

**Comment by bbelderbos** [comment]
Thanks @ignazwrangel, I agree the description can use a bit more details/specs

@hobojoe1848 maybe we give a hint about the expected outputs, or even a test they can use (mocking out sleep). 

I dug up our traffic light script from our 100 days: https://github.com/pybites/100DaysOfCode/blob/master/029/traffic_lights.py

**Comment by hobojoe1848** [comment]
Hi @ignazwrangel! Thanks for the feedback mate. You're exactly right.

Sometimes when you write these things, after spending 3-4 months creating it, it's easy to forget that no one else is going to know what was floating around in your head haha!

I've added some instructions in there re what to do.

Let us know what you think!

Cheers
Julian
