### ISSUE TITLE
Consider rewording

### ISSUE THREAD

**Issue by possnfiffer** [talkpython/100daysofcode-with-python-course#2]
The first sentence on the following page is hard to read, it tripped me up and I caught myself re-reading it. 

https://github.com/talkpython/100daysofcode-with-python-course/blob/master/days/25-27-error-handling/README.md

> One of the key differentiators of professional programs and scripts thrown together by beginners is pro app does not crash.

Perhaps it could be re-written like one of the following:

One of the key differentiators of professional programs and scripts thrown together by beginners is that the pro app does not crash.

One of the key differentiators of professional programs and scripts thrown together by beginners is the pro app does not crash.

**Comment by mikeckennedy** [comment]
Thanks a bunch @possnfiffer I updated the README with your suggestion.
