### ISSUE TITLE
urlretrieve function 

### ISSUE THREAD

**Issue by midwfapao** [talkpython/100daysofcode-with-python-course#22]
This function can't use anymore since is removed from python.

How can I handle this problem? Are there any function can be replaced with this function?

** Days 4-6

**Comment by bbelderbos** [comment]
What version of Python are you using' `from urllib.request import urlretrieve` runs fine on 3.6 and 3.7 for me. You can also use `requests` (after pip installing it)

**Comment by midwfapao** [comment]
Sorry for that, my mistake. But problem is, I couldn't find any solution for 'take the csv file from web and process with another csv file from my computer' can you help me ? 

On the requests library, I get the file from web. File dot content doesn't exist. So, I tried to file dot(.) text. It works. But if I open my csv file which is my computer, I couln't copy the content of csv file. Tried to csv.reader() etc. Do you know is there any simple solution for this?
