### ISSUE TITLE
Possible misleading typo in 22-24 Decorators

### ISSUE THREAD

**Issue by benkawecki** [talkpython/100daysofcode-with-python-course#25]
In [100daysofcode-with-python-course/days/22-24-decorators/decorators.ipynb](https://github.com/talkpython/100daysofcode-with-python-course/blob/master/days/22-24-decorators/decorators.ipynb) under "Second day: a practical exercise" you list the following block of code:

```python 
@make_html('p')
@make_html('strong')
def get_text(text):
    pass
```
As the problem is listed now it implies that make_html decorator should be responsible for printing the test instead of just adding tags. In the linked pybite <code>get_text()</code> is defined as:

```python
def get_text(text):
    print(text)
```

Is that <code>pass</code> in the jupyter notebook a typo, which instead should be <code>print(text)</code>?

**Comment by bbelderbos** [comment]
Hey @benkawecki I agree, `print(text)` would be better/clearer. I updated the notebook. Thanks.
