### ISSUE TITLE
 video 'hello test world' 

### ISSUE THREAD

**Issue by elephantarms** [talkpython/100daysofcode-with-python-course#27]
This video was very disappointing . Your explanation of the command line arguments was extremely superficial. I cannot get it to work. I am starting to regret buying this course. can you point to a better, more detailed explanation of how to run pytest. Thanks.

**Comment by bbelderbos** [comment]
Thanks @elephantarms for your feedback. I can definitely add some command line flags in the README if that helps, but for basic usage (like in this video), you don't typically need them.
 
Could you please let me know the issue you are hitting so I can look into a possible solution for you?

Cheers
Bob

**Comment by elephantarms** [comment]
Thanks for getting back to me. I was trying to do the examples on the
pycharm terminal and kept getting error messages. do i need to do this on
the command line? i tried to do this running on a regular pycharm
environment and got error messages. Thanks.

**Comment by hobojoe1848** [comment]
Hi @elephantarms, (love the username btw!),

Can you paste the errors please?
We need to see the exact error messages so we can figure out what's going wrong.

Thanks mate!
Cheers
Julian

**Comment by elephantarms** [comment]
command.....
C:\Users\gregt\PycharmProjects\100_days>pytest test_hello_name.py

This is the error message when i run in the pycharm terminal....

'pytest' is not recognized as an internal or external command,
operable program or batch file.

When I run the program on pycharm(not via terminal) the assert is just a
normal assert statement, it does seem to be utilizing pytest like on your
video

Thanks.

**Comment by bbelderbos** [comment]
`pytest` is an external dependency and therefore you need to `pip install` it, typically into a virtual environment. See the README where I just added a link to an article we did on virtual environments: https://github.com/talkpython/100daysofcode-with-python-course/blob/master/days/10-12-pytest/README.md. HTH and let us know if you need more help ...

**Comment by elephantarms** [comment]
Thanks, I did have pytest installed in my pycharm environment. Does pytest
need to be run from the command line? Thanks.

**Comment by bbelderbos** [comment]
Both are valid options. I only use it from the command line as shown in the lesson. I don't use `pycharm`, but check out the docs here: https://www.jetbrains.com/help/pycharm/pytest.html + `pytest` master Brian Okken recorded a webinar on the topic if you want to dive deep: https://www.youtube.com/watch?v=ixqeebhUa-w

HTH
Bob

**Comment by elephantarms** [comment]
Thanks!

**Comment by mikeckennedy** [comment]
Hi guys, thanks for all the details Bob. @elephantarms you can also just add a run config for pytest in PyCharm. See this image for all you need. Just pick the tests file to run:

![screen shot 2018-12-07 at 2 51 13 pm](https://user-images.githubusercontent.com/2035561/49676712-a9901880-fa2f-11e8-8e70-a6cf03b4c168.png)

**Comment by elephantarms** [comment]
Thanks Michael
