### ISSUE TITLE
The subtitles for the deque and first concept videos (days 4-6) are swapped around. 

### ISSUE THREAD

**Issue by Anthlis** [talkpython/100daysofcode-with-python-course#34]
I followed the collections chapter tonight and found that the subtitles for the deque and first concept videos (days 4-6) are swapped around. I.e. the concept subtitles were shown during the deque video and vice-versa. (BTW - this is my first ever issue raised on GitHub so I hope I've done this right!).

**Comment by mikeckennedy** [comment]
Thanks for letting us know! I just updated them. And yeah, this format and style is the perfect place to report issues like this on GitHub. ;)
