### ISSUE TITLE
Missing README for days 04-06

### ISSUE THREAD

**Issue by conorcunningham** [talkpython/100daysofcode-with-python-course#36]
G'day Michael and team,

There is no README file for days 04-06. I managed to navigate to the exercise eventually from the link in the video, but was under the impression that all days would have README instructions.

Cheers,

Conor

**Comment by bbelderbos** [comment]
Thanks for pointing this out @conorcunningham, this is a pattern for my lessons because I used Jupyter notebooks. I agree every 3 days should have a README, so I will make sure my lesson get one added each. How is the course going so far? 
Cheers, 
Bob

**Comment by conorcunningham** [comment]
G'day @bbelderbos ,

Ah, I see. I must admit that I missed that it was a Jupyter file! Regardless, the course is coming along well and I've completed days 1-9. Looking forward to getting stuck into the rest of it.
Thanks a million for getting back to me.

Cheers,
Conor

**Comment by bbelderbos** [comment]
@conorcunningham happy to hear! I just added README files to all my lessons so the repo is more consistent. Thanks again for reporting this.
