### ISSUE TITLE
Pyperclip does not work correctly under Linux

### ISSUE THREAD

**Issue by aojanzen** [talkpython/100daysofcode-with-python-course#46]
I had issues with pyperclip. Copying text to the clipboard did not work. Found the solution for my problem on the pypi page of pyperclip:

"... On Linux, this module makes use of the xclip or xsel commands, which should come with the os. Otherwise run “sudo apt-get install xclip” or “sudo apt-get install xsel” (Note: xsel does not always seem to work.)

Otherwise on Linux, you will need the gtk or PyQt4 modules installed."

Everything works fine now, after I have installed xclip.

**Comment by mikeckennedy** [comment]
Thanks for the heads up @aojanzen I added a note about this in the your turn readme and linked back here: https://github.com/talkpython/100daysofcode-with-python-course/blob/master/days/67-69-pyperclip/README.md
