### ISSUE TITLE
Link in day 5 is broken

### ISSUE THREAD

**Issue by bluthej** [talkpython/100daysofcode-with-python-course#61]
Hi, started the course a few days ago and I noticed that the link to [PyBite 13](https://pybit.es/codechallenge13.htmlthat) that appears in [day 5](https://github.com/talkpython/100daysofcode-with-python-course/tree/master/days/04-06-collections#day-2-practice-using-movie-data ) is broken. I get a 404 error.

Also, I think that the url given in the notebook to retrieve the data is not valid anymore. 

Thanks Michael for all that you put out there for people to level up in Python 🙏
I'm a big fan of TalkPythonToMe

**Comment by bbelderbos** [comment]
Thanks @bluthej, I fixed the link, this happened when we migrated the blog to Wordpress. 

The data link works for me:
https://raw.githubusercontent.com/sundeepblue/movie_rating_prediction/master/movie_metadata.csv

This also became free Bite 30 as well, if you want to code it there: 
https://codechalleng.es/bites/30/
