### ISSUE TITLE
Link for the pytest fixtures article (day 12) is broken

### ISSUE THREAD

**Issue by bluthej** [talkpython/100daysofcode-with-python-course#63]
The link to the pytest fixture article in the [day 12](https://github.com/talkpython/100daysofcode-with-python-course/tree/master/days/10-12-pytest#day-n2-your-turn-write-a-fixture) section is broken.

It points to https://pybit.es/pytest-fixtures.html, whereas it should point to (thanks Google!) https://pybit.es/articles/pytest-fixtures/.

**Comment by bbelderbos** [comment]
Thanks @bluthej, fixed it.
