### ISSUE TITLE
isn't there a group you created 

### ISSUE THREAD

**Issue by yosefco3** [talkpython/100daysofcode-with-python-course#9]
for the members of "100 days challenge" ? 
you know , special group we could share , get advice etc. and not in my twitter ?

**Comment by hobojoe1848** [comment]
Hi @yosefco3, we have a channel in our private Slack channel dedicated to the course.

Once you've got your profile setup on the code challenges platform you can see it under Settings: https://codechalleng.es/settings/

Thanks!
Julian

**Comment by yosefco3** [comment]
Hi julian thanks on the answer , but in the url it's want from me to activate the "licence key" of PyByte by paying 10$ to a month , but i bought the course ....

**Comment by pybites** [comment]
You need to confirm your email, once done you have an opt in for slack. See you there :)

**Comment by hobojoe1848** [comment]
Awesome, you're in! Will close this off now.

Cheers
Julian
